"""add product uom column

Revision ID: 8066f55df42e
Revises: 5cf89b5eb404
Create Date: 2025-11-22 10:47:35.369645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8066f55df42e'
down_revision: Union[str, Sequence[str], None] = '5cf89b5eb404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uom', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'uom')
    # ### end Alembic commands ###
