"""prod: add warehouses, partners, quants, ledger, reorder rules, constraints, timestamps

Revision ID: cdde8a6947d7
Revises: 8066f55df42e
Create Date: 2025-11-22 11:18:12.572219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdde8a6947d7'
down_revision: Union[str, Sequence[str], None] = '8066f55df42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner_type', sa.Enum('vendor', 'customer', name='partnertype'), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('reorder_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('min_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('max_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reorder_rules_id'), 'reorder_rules', ['id'], unique=False)
    op.create_index(op.f('ix_reorder_rules_product_id'), 'reorder_rules', ['product_id'], unique=False)
    op.create_index(op.f('ix_reorder_rules_warehouse_id'), 'reorder_rules', ['warehouse_id'], unique=False)
    op.create_table('stockquants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reserved_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_stockquant_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='uq_stockquant_product_location')
    )
    op.create_index(op.f('ix_stockquants_id'), 'stockquants', ['id'], unique=False)
    op.create_index(op.f('ix_stockquants_location_id'), 'stockquants', ['location_id'], unique=False)
    op.create_index(op.f('ix_stockquants_product_id'), 'stockquants', ['product_id'], unique=False)
    op.create_table('stockledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('change_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('resulting_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.Column('operation_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['stockmoves.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['stockoperations.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockledger_id'), 'stockledger', ['id'], unique=False)
    op.create_index(op.f('ix_stockledger_location_id'), 'stockledger', ['location_id'], unique=False)
    op.create_index(op.f('ix_stockledger_move_id'), 'stockledger', ['move_id'], unique=False)
    op.create_index(op.f('ix_stockledger_operation_id'), 'stockledger', ['operation_id'], unique=False)
    op.create_index(op.f('ix_stockledger_performed_by_id'), 'stockledger', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_stockledger_product_id'), 'stockledger', ['product_id'], unique=False)
    op.add_column('locations', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_locations_warehouse_id'), 'locations', ['warehouse_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('products', sa.Column('initial_stock', sa.Numeric(precision=14, scale=4), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # Create the ENUM type in Postgres before adding the column that uses it
    operation_type_enum = sa.Enum('receipt', 'delivery', 'internal', 'adjustment', name='operationtype')
    operation_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('stockoperations', sa.Column('operation_type', operation_type_enum, nullable=False))
    op.add_column('stockoperations', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('stockoperations', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('stockoperations', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('stockoperations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_stockoperations_created_by_id'), 'stockoperations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_stockoperations_partner_id'), 'stockoperations', ['partner_id'], unique=False)
    op.create_foreign_key(None, 'stockoperations', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'stockoperations', 'partners', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stockoperations', type_='foreignkey')
    op.drop_constraint(None, 'stockoperations', type_='foreignkey')
    op.drop_index(op.f('ix_stockoperations_partner_id'), table_name='stockoperations')
    op.drop_index(op.f('ix_stockoperations_created_by_id'), table_name='stockoperations')
    op.drop_column('stockoperations', 'updated_at')
    op.drop_column('stockoperations', 'created_at')
    op.drop_column('stockoperations', 'created_by_id')
    op.drop_column('stockoperations', 'partner_id')
    op.drop_column('stockoperations', 'operation_type')
    # Drop the ENUM type after removing the column
    operation_type_enum = sa.Enum('receipt', 'delivery', 'internal', 'adjustment', name='operationtype')
    operation_type_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'initial_stock')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_warehouse_id'), table_name='locations')
    op.drop_column('locations', 'warehouse_id')
    op.drop_index(op.f('ix_stockledger_product_id'), table_name='stockledger')
    op.drop_index(op.f('ix_stockledger_performed_by_id'), table_name='stockledger')
    op.drop_index(op.f('ix_stockledger_operation_id'), table_name='stockledger')
    op.drop_index(op.f('ix_stockledger_move_id'), table_name='stockledger')
    op.drop_index(op.f('ix_stockledger_location_id'), table_name='stockledger')
    op.drop_index(op.f('ix_stockledger_id'), table_name='stockledger')
    op.drop_table('stockledger')
    op.drop_index(op.f('ix_stockquants_product_id'), table_name='stockquants')
    op.drop_index(op.f('ix_stockquants_location_id'), table_name='stockquants')
    op.drop_index(op.f('ix_stockquants_id'), table_name='stockquants')
    op.drop_table('stockquants')
    op.drop_index(op.f('ix_reorder_rules_warehouse_id'), table_name='reorder_rules')
    op.drop_index(op.f('ix_reorder_rules_product_id'), table_name='reorder_rules')
    op.drop_index(op.f('ix_reorder_rules_id'), table_name='reorder_rules')
    op.drop_table('reorder_rules')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    # ### end Alembic commands ###
